.travis.yml
travis/deploy_yqlplus_language.sh

add a script for yqlplus_language api

debug bintray deploy

---

.travis.yml
travis/deploy.sh

enable bintray deploy

---

yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/source/ExportUnitGenerator.java

Export class loaders are not registered

Add UDF classloader to scope to fix no class found error if program only has UDFs

---

travis/deploy.sh

adjust deploy

---

pom.xml
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/sources/MethodTracingSource.java

The unit test is updated to cope with windows 10 development environment.  I'm open to changing the unit test if there is a better approach to this test.

Update project pom build plugins to current versions.  Require jdk and source to 1.9

---

pom.xml
yqlplus_stdlib/pom.xml
yqlplus_stdlib/src/main/java/com/yahoo/yqlplus/util/DateTime.java
yqlplus_stdlib/src/test/java/com/yahoo/yqlplus/util/DateTimeTest.java

functionality exposed in jdk8 and later versions

Remove org.threeten.threetenbp and standardize on JSR-310 java.time

---

yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/plan/types/base/ArrayIndexAdapter.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/sources/CollectionFunctionsUdf.java

Fixing issue https://github.com/yahoo/yql-plus/issues/55

Emit count and idx write for ArrayIndexAdapter

---

yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java
yqlplus_language/src/main/java/com/yahoo/yqlplus/language/parser/ProgramParser.java

Fix parsing exception of the case select statement without source

---

.travis.yml

add jdk branches to build

---

yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/compiler/CodeEmitter.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/plan/types/base/FieldAssignableValue.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/plan/types/base/ReflectivePropertyAdapter.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/sources/GenericFieldResultSource.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/sources/SampleResultSource.java

The root cause is should use type not genericType.

Add cast for generic return type if necessary

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Preparing release 1.0.13

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Starting 1.0.14-SNAPSHOT

---

.travis.yml
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/tasks/GraphPlanner.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/sources/SampleExecutionSource.java

Am not confident in the fix. So just comment out the code I think causes the problem

initial attempt to fix parallel execution problem

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Prepare releasing 1.0.14

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Starting 1.0.15-SNAPSHOT

---

yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/guice/PlannerCompilerModule.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/compiler/streams/PlanProgramCompileOptions.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/tasks/GraphPlanner.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/DeepJoinTest.java
yqlplus_engine/src/test/java/com/yahoo/yqlplus/engine/java/JavaProgramCompilerTest.java

revert wrong commit
revert wrong commit and copy right

Improve compile option login

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Prepare releasing 1.0.15

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Starting 1.0.16-SNAPSHOT

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/generate/ProgramInvocation.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/java/runtime/TimeoutHandler.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/java/sequences/Sequences.java
yqlplus_engine/src/main/java/com/yahoo/yqlplus/engine/internal/scope/ScopedTracingExecutor.java
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_source_api/src/main/java/com/yahoo/yqlplus/api/types/Annotations.java

Upgrade guava to 24.1.1

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Prepare releasing 1.0.16

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Starting 1.0.17-SNAPSHOT

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_language/pom.xml

align jackson-core to 2.9.10

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Prepare releasing 1.0.17

---

pom.xml
yqlplus_engine/pom.xml
yqlplus_javadocs/pom.xml
yqlplus_language/pom.xml
yqlplus_source_api/pom.xml
yqlplus_stdlib/pom.xml

Starting 1.0.18-SNAPSHOT
